[package]
name = "itry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.6" }
tokio = { version = "1.18.2", features = ["macros"] }
